%% RUNSTAGE5VISUALIZATION Simulate, validate, and animate waypoint mission
clc;
close all;

stage5Folder = fileparts(mfilename('fullpath'));
projectFolder = fileparts(stage5Folder);
addpath(stage5Folder,'-begin');

candidateFolders = [ ...
    fullfile(projectFolder,"drone_stage_4_waypoints"); ...
    fullfile(projectFolder,"drone_stage4_waypoints"); ...
    fullfile(projectFolder,"drone_stage_3"); ...
    fullfile(projectFolder,"drone_stage3_estimation")];
for folderIndex = 1:numel(candidateFolders)
    if isfolder(candidateFolders(folderIndex))
        addpath(candidateFolders(folderIndex),'-begin');
    end
end

requiredFunctions = [ ...
    "waypointTrajectoryStage4"; ...
    "flightControllerStage4Waypoints"; ...
    "sensorModelStage3"; ...
    "stateEstimatorStage3"; ...
    "quadDynamicsStage3"; ...
    "animateWaypointMissionStage5"];
for functionIndex = 1:numel(requiredFunctions)
    if isempty(which(requiredFunctions(functionIndex)))
        error('Required function is not on the MATLAB path: %s', ...
            requiredFunctions(functionIndex));
    end
end

modelName = "quadrotor_stage4_waypoints";
modelFile = which(modelName+".slx");
if isempty(modelFile)
    error(['quadrotor_stage4_waypoints.slx is not on the MATLAB path. ', ...
           'Add the folder containing the working waypoint model.']);
end
fprintf('Using waypoint model: %s\n',modelFile);

clear sensorModelStage3 stateEstimatorStage3
out = sim(modelName);
stage5Report = validateStage5Integration(out);
if ~stage5Report.Passed
    error('Stage 5 validation failed. Correct the reported issue before animation.');
end

animateWaypointMissionStage5(out, ...
    'PlaybackSpeed',1.7, ...
    'FrameRate',30, ...
    'CameraMode','fixed', ...
    'ShowEstimate',true, ...
    'ShowGPS',true);
