function [agent,trainingStats] = trainPPOStage13(maxEpisodes)
%TRAINPPOSTAGE13 Train CBF-filtered PPO in the surrogate environment.

if nargin<1,maxEpisodes=800;end
rng(1313,'twister');
if isempty(which('gatThreatWeightsStage12.mat'))
    error('Train Stage 12 first and add its folder to the MATLAB path.');
end
[environment,observationInfo,actionInfo]=createSkyGraphPPOEnvironmentStage13();
validateEnvironment(environment);
agent=createPPOAgentStage13(observationInfo,actionInfo);

saveDirectory=fullfile(fileparts(mfilename('fullpath')),'savedAgentsStage13');
if ~isfolder(saveDirectory),mkdir(saveDirectory);end
trainingOptions=rlTrainingOptions( ...
    MaxEpisodes=maxEpisodes, ...
    MaxStepsPerEpisode=200, ...
    ScoreAveragingWindowLength=30, ...
    StopTrainingCriteria="AverageReward", ...
    StopTrainingValue=25, ...
    SaveAgentCriteria="EpisodeReward", ...
    SaveAgentValue=20, ...
    SaveAgentDirectory=saveDirectory, ...
    Plots="training-progress", ...
    Verbose=true);

trainingStats=train(agent,environment,trainingOptions);
outputFile=fullfile(fileparts(mfilename('fullpath')),'ppoAgentStage13.mat');
save(outputFile,'agent','trainingStats','-v7.3');
fprintf('Saved trained PPO agent: %s\n',outputFile);
end
