function report=validateSkyGraphStage14(simulationOutput)
%VALIDATESKYGRAPHSTAGE14 Check all logs required by complete visualization.

spec={ ...
 {'true_state14_log','true_state8_log','true_state4w_log'},16,'true state'; ...
 {'estimated_state14_log','estimated_state4w_log','estimated_state3_log'},12,'estimated state'; ...
 {'trajectory14_log','trajectory4w_log'},10,'trajectory'; ...
 {'scenario8_position_log'},48,'scenario positions'; ...
 {'scenario8_radius_log'},16,'scenario radii'; ...
 {'scenario8_type_log'},16,'scenario types'; ...
 {'scenario8_active_log'},16,'scenario active'; ...
 {'tof8_distance_log'},10,'ToF ranges'; ...
 {'tof8_valid_log'},10,'ToF valid'; ...
 {'tof8_packet_age_log'},1,'packet age'; ...
 {'track9_position_log'},48,'track positions'; ...
 {'track9_id_log'},16,'track IDs'; ...
 {'track9_type_log'},16,'track types'; ...
 {'track9_active_log'},16,'track active'; ...
 {'track9_confidence_log'},16,'track confidence'; ...
 {'graph10_mask_log'},17,'graph mask'; ...
 {'graph10_id_log'},17,'graph IDs'; ...
 {'graph10_adjacency_log'},289,'graph adjacency'; ...
 {'gat12_threat_log'},17,'GAT threat'; ...
 {'gat12_attention_log'},289,'GAT attention'; ...
 {'gat12_top_id_log'},5,'GAT top IDs'; ...
 {'gat12_top_score_log'},5,'GAT top scores'; ...
 {'ppo13_selected_log'},3,'selected nominal action'; ...
 {'ppo13_source_log'},1,'policy source'; ...
 {'cbf11_safe_log'},3,'CBF safe action'; ...
 {'cbf11_intervention_log'},1,'CBF intervention'; ...
 {'cbf11_slack_log'},1,'CBF slack'; ...
 {'cbf11_separation_log'},1,'minimum separation'};

fprintf('\nSTAGE 14 LOG VALIDATION\n');
fprintf('=======================\n');
report=struct;report.Passed=true;report.ResolvedNames=strings(size(spec,1),1);
for k=1:size(spec,1)
    candidates=spec{k,1};width=spec{k,2};description=spec{k,3};
    try
        [time,data,name]=readAny14(simulationOutput,candidates,width);
        if any(~isfinite(data(:)))
            error('%s contains NaN or Inf.',name);
        end
        report.ResolvedNames(k)=name;
        fprintf('PASS  %-24s %-28s %d samples\n',description,name,numel(time));
    catch exception
        report.Passed=false;
        fprintf('FAIL  %-24s %s\n',description,exception.message);
    end
end

if report.Passed
    [time,trueState]=readAny14(simulationOutput,spec{1,1},16);
    [~,intervention]=readAny14(simulationOutput,{'cbf11_intervention_log'},1);
    [~,slack]=readAny14(simulationOutput,{'cbf11_slack_log'},1);
    [~,separation]=readAny14(simulationOutput,{'cbf11_separation_log'},1);
    report.Duration=time(end)-time(1);
    report.MaximumMotorSpeed=max(trueState(:,13:16),[],1);
    report.CBFInterventionRate=mean(intervention>0.5);
    report.MaximumSlack=max(slack);
    report.MinimumSeparation=min(separation);
    fprintf('Duration: %.2f s\n',report.Duration);
    fprintf('CBF intervention rate: %.1f %%\n',100*report.CBFInterventionRate);
    fprintf('Maximum slack: %.4f\n',report.MaximumSlack);
    fprintf('Minimum separation: %.4f m\n',report.MinimumSeparation);
    fprintf('RESULT: PASS - Stage 14 visualization data is ready.\n\n');
else
    error('Stage 14 required logs are incomplete.');
end
end

function [time,data,resolvedName]=readAny14(out,candidates,width)
names=out.who;resolvedName="";signal=[];
for k=1:numel(candidates)
    name=char(candidates{k});
    if any(strcmp(names,name)),signal=out.get(name);resolvedName=string(name);break;end
    if evalin('base',['exist(''' name ''',''var'')'])
        signal=evalin('base',name);resolvedName=string(name);break;
    end
end
if isempty(signal),error('Missing: %s',strjoin(string(candidates),', '));end
time=signal.Time(:);data=squeeze(signal.Data);
if isvector(data),data=data(:);
elseif size(data,1)==numel(time)
elseif size(data,2)==numel(time),data=data.';
else,error('%s has incompatible dimensions.',resolvedName);end
if size(data,2)<width,error('%s needs %d columns.',resolvedName,width);end
data=data(:,1:width);
end
