%% CONFIGURESTAGE3BLOCKS Set digital block rates and model solver
% Run this after creating and naming the blocks exactly as in the guide.

model = "quadrotor_stage3";
load_system(model);

discreteBlocks = [ ...
    model+"/Sensor Model"; ...
    model+"/State Estimator"; ...
    model+"/Flight Controller"; ...
    model+"/Position Error"];

for k = 1:numel(discreteBlocks)
    configuration = get_param(discreteBlocks(k), ...
        "MATLABFunctionConfiguration");
    configuration.UpdateMethod = "Discrete";
    configuration.SampleTime = "0.005";
    fprintf('Configured %s at 0.005 s.\n',discreteBlocks(k));
end

set_param(model, ...
    'StartTime','0', ...
    'StopTime','18', ...
    'SolverType','Fixed-step', ...
    'Solver','ode4', ...
    'FixedStep','0.005');

save_system(model);
fprintf('Configured and saved %s.slx.\n',model);
